export function popoulateBigFontList(bigFontList: string[])         {
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |      __      | |" );
    bigFontList.push( "| |     /  \\     | |" );
    bigFontList.push( "| |    / /\\ \\    | |" );
    bigFontList.push( "| |   / ____ \\   | |" );
    bigFontList.push( "| | _/ /    \\ \\_ | |" );
    bigFontList.push( "| ||____|  |____|| |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   ______     | |" );
    bigFontList.push( "| |  |_   _ \\    | |" );
    bigFontList.push( "| |    | |_) |   | |" );
    bigFontList.push( "| |    |  __'.   | |" );
    bigFontList.push( "| |   _| |__) |  | |" );
    bigFontList.push( "| |  |_______/   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     ______   | |" );
    bigFontList.push( "| |   .' ___  |  | |" );
    bigFontList.push( "| |  / .'   \\_|  | |" );
    bigFontList.push( "| |  | |         | |" );
    bigFontList.push( "| |  \\ `.___.'\\  | |" );
    bigFontList.push( "| |   `._____.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  ________    | |" );
    bigFontList.push( "| | |_   ___ `.  | |" );
    bigFontList.push( "| |   | |   `. \\ | |" );
    bigFontList.push( "| |   | |    | | | |" );
    bigFontList.push( "| |  _| |___.' / | |" );
    bigFontList.push( "| | |________.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  _________   | |" );
    bigFontList.push( "| | |_   ___  |  | |" );
    bigFontList.push( "| |   | |_  \\_|  | |" );
    bigFontList.push( "| |   |  _|  _   | |" );
    bigFontList.push( "| |  _| |___/ |  | |" );
    bigFontList.push( "| | |_________|  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  _________   | |" );
    bigFontList.push( "| | |_   ___  |  | |" );
    bigFontList.push( "| |   | |_  \\_|  | |" );
    bigFontList.push( "| |   |  _|      | |" );
    bigFontList.push( "| |  _| |_       | |" );
    bigFontList.push( "| | |_____|      | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    ______    | |" );
    bigFontList.push( "| |  .' ___  |   | |" );
    bigFontList.push( "| | / .'   \\_|   | |" );
    bigFontList.push( "| | | |    ____  | |" );
    bigFontList.push( "| | \\ `.___]  _| | |" );
    bigFontList.push( "| |  `._____.'   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  ____  ____  | |" );
    bigFontList.push( "| | |_   ||   _| | |" );
    bigFontList.push( "| |   | |__| |   | |" );
    bigFontList.push( "| |   |  __  |   | |" );
    bigFontList.push( "| |  _| |  | |_  | |" );
    bigFontList.push( "| | |____||____| | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     _____    | |" );
    bigFontList.push( "| |    |_   _|   | |" );
    bigFontList.push( "| |      | |     | |" );
    bigFontList.push( "| |      | |     | |" );
    bigFontList.push( "| |     _| |_    | |" );
    bigFontList.push( "| |    |_____|   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     _____    | |" );
    bigFontList.push( "| |    |_   _|   | |" );
    bigFontList.push( "| |      | |     | |" );
    bigFontList.push( "| |   _  | |     | |" );
    bigFontList.push( "| |  | |_' |     | |" );
    bigFontList.push( "| |  `.___.'     | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  ___  ____   | |" );
    bigFontList.push( "| | |_  ||_  _|  | |" );
    bigFontList.push( "| |   | |_/ /    | |" );
    bigFontList.push( "| |   |  __'.    | |" );
    bigFontList.push( "| |  _| |  \\ \\_  | |" );
    bigFontList.push( "| | |____||____| | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   _____      | |" );
    bigFontList.push( "| |  |_   _|     | |" );
    bigFontList.push( "| |    | |       | |" );
    bigFontList.push( "| |    | |   _   | |" );
    bigFontList.push( "| |   _| |__/ |  | |" );
    bigFontList.push( "| |  |________|  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| | ____    ____ | |" );
    bigFontList.push( "| ||_   \\  /   _|| |" );
    bigFontList.push( "| |  |   \\/   |  | |" );
    bigFontList.push( "| |  | |\\  /| |  | |" );
    bigFontList.push( "| | _| |_\\/_| |_ | |" );
    bigFontList.push( "| ||_____||_____|| |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .-----------------." );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| | ____  _____  | |" );
    bigFontList.push( "| ||_   \\|_   _| | |" );
    bigFontList.push( "| |  |   \\ | |   | |" );
    bigFontList.push( "| |  | |\\ \\| |   | |" );
    bigFontList.push( "| | _| |_\\   |_  | |" );
    bigFontList.push( "| ||_____|\\____| | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     ____     | |" );
    bigFontList.push( "| |   .'    `.   | |" );
    bigFontList.push( "| |  /  .--.  \\  | |" );
    bigFontList.push( "| |  | |    | |  | |" );
    bigFontList.push( "| |  \\  `--'  /  | |" );
    bigFontList.push( "| |   `.____.'   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   ______     | |" );
    bigFontList.push( "| |  |_   __ \\   | |" );
    bigFontList.push( "| |    | |__) |  | |" );
    bigFontList.push( "| |    |  ___/   | |" );
    bigFontList.push( "| |   _| |_      | |" );
    bigFontList.push( "| |  |_____|     | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    ___       | |" );
    bigFontList.push( "| |  .'   '.     | |" );
    bigFontList.push( "| | /  .-.  \\    | |" );
    bigFontList.push( "| | | |   | |    | |" );
    bigFontList.push( "| | \\  `-'  \\_   | |" );
    bigFontList.push( "| |  `.___.\\__|  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  _______     | |" );
    bigFontList.push( "| | |_   __ \\    | |" );
    bigFontList.push( "| |   | |__) |   | |" );
    bigFontList.push( "| |   |  __ /    | |" );
    bigFontList.push( "| |  _| |  \\ \\_  | |" );
    bigFontList.push( "| | |____| |___| | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    _______   | |" );
    bigFontList.push( "| |   /  ___  |  | |" );
    bigFontList.push( "| |  |  (__ \\_|  | |" );
    bigFontList.push( "| |   '.___`-.   | |" );
    bigFontList.push( "| |  |`\\____) |  | |" );
    bigFontList.push( "| |  |_______.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  _________   | |" );
    bigFontList.push( "| | |  _   _  |  | |" );
    bigFontList.push( "| | |_/ | | \\_|  | |" );
    bigFontList.push( "| |     | |      | |" );
    bigFontList.push( "| |    _| |_     | |" );
    bigFontList.push( "| |   |_____|    | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| | _____  _____ | |" );
    bigFontList.push( "| ||_   _||_   _|| |" );
    bigFontList.push( "| |  | |    | |  | |" );
    bigFontList.push( "| |  | '    ' |  | |" );
    bigFontList.push( "| |   \\ `--' /   | |" );
    bigFontList.push( "| |    `.__.'    | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| | ____   ____  | |" );
    bigFontList.push( "| ||_  _| |_  _| | |" );
    bigFontList.push( "| |  \\ \\   / /   | |" );
    bigFontList.push( "| |   \\ \\ / /    | |" );
    bigFontList.push( "| |    \\ ' /     | |" );
    bigFontList.push( "| |     \\_/      | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| | _____  _____ | |" );
    bigFontList.push( "| ||_   _||_   _|| |" );
    bigFontList.push( "| |  | | /\\ | |  | |" );
    bigFontList.push( "| |  | |/  \\| |  | |" );
    bigFontList.push( "| |  |   /\\   |  | |" );
    bigFontList.push( "| |  |__/  \\__|  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  ____  ____  | |" );
    bigFontList.push( "| | |_  _||_  _| | |" );
    bigFontList.push( "| |   \\ \\  / /   | |" );
    bigFontList.push( "| |    > `' <    | |" );
    bigFontList.push( "| |  _/ /'`\\ \\_  | |" );
    bigFontList.push( "| | |____||____| | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |  ____  ____  | |" );
    bigFontList.push( "| | |_  _||_  _| | |" );
    bigFontList.push( "| |   \\ \\  / /   | |" );
    bigFontList.push( "| |    \\ \\/ /    | |" );
    bigFontList.push( "| |    _|  |_    | |" );
    bigFontList.push( "| |   |______|   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   ________   | |" );
    bigFontList.push( "| |  |  __   _|  | |" );
    bigFontList.push( "| |  |_/  / /    | |" );
    bigFontList.push( "| |     .'.' _   | |" );
    bigFontList.push( "| |   _/ /__/ |  | |" );
    bigFontList.push( "| |  |________|  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );
    bigFontList.push( "     " );

    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     __       | |" );
    bigFontList.push( "| |    /  |      | |" );
    bigFontList.push( "| |    `| |      | |" );
    bigFontList.push( "| |     | |      | |" );
    bigFontList.push( "| |    _| |_     | |" );
    bigFontList.push( "| |   |_____|    | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    _____     | |" );
    bigFontList.push( "| |   / ___ `.   | |" );
    bigFontList.push( "| |  |_/___) |   | |" );
    bigFontList.push( "| |   .'____.'   | |" );
    bigFontList.push( "| |  / /____     | |" );
    bigFontList.push( "| |  |_______|   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    ______    | |" );
    bigFontList.push( "| |   / ____ `.  | |" );
    bigFontList.push( "| |   `'  __) |  | |" );
    bigFontList.push( "| |   _  |__ '.  | |" );
    bigFontList.push( "| |  | \\____) |  | |" );
    bigFontList.push( "| |   \\______.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   _    _     | |" );
    bigFontList.push( "| |  | |  | |    | |" );
    bigFontList.push( "| |  | |__| |_   | |" );
    bigFontList.push( "| |  |____   _|  | |" );
    bigFontList.push( "| |      _| |_   | |" );
    bigFontList.push( "| |     |_____|  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   _______    | |" );
    bigFontList.push( "| |  |  _____|   | |" );
    bigFontList.push( "| |  | |____     | |" );
    bigFontList.push( "| |  '_.____''.  | |" );
    bigFontList.push( "| |  | \\____) |  | |" );
    bigFontList.push( "| |   \\______.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    ______    | |" );
    bigFontList.push( "| |  .' ____ \\   | |" );
    bigFontList.push( "| |  | |____\\_|  | |" );
    bigFontList.push( "| |  | '____`'.  | |" );
    bigFontList.push( "| |  | (____) |  | |" );
    bigFontList.push( "| |  '.______.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |   _______    | |" );
    bigFontList.push( "| |  |  ___  |   | |" );
    bigFontList.push( "| |  |_/  / /    | |" );
    bigFontList.push( "| |      / /     | |" );
    bigFontList.push( "| |     / /      | |" );
    bigFontList.push( "| |    /_/       | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     ____     | |" );
    bigFontList.push( "| |   .' __ '.   | |" );
    bigFontList.push( "| |   | (__) |   | |" );
    bigFontList.push( "| |   .`____'.   | |" );
    bigFontList.push( "| |  | (____) |  | |" );
    bigFontList.push( "| |  `.______.'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |    ______    | |" );
    bigFontList.push( "| |  .' ____ '.  | |" );
    bigFontList.push( "| |  | (____) |  | |" );
    bigFontList.push( "| |  '_.____. |  | |" );
    bigFontList.push( "| |  | \\____| |  | |" );
    bigFontList.push( "| |   \\______,'  | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );

    bigFontList.push( " .----------------. " );
    bigFontList.push( "| .--------------. |" );
    bigFontList.push( "| |     ____     | |" );
    bigFontList.push( "| |   .'    '.   | |" );
    bigFontList.push( "| |  |  .--.  |  | |" );
    bigFontList.push( "| |  | |    | |  | |" );
    bigFontList.push( "| |  |  `--'  |  | |" );
    bigFontList.push( "| |   '.____.'   | |" );
    bigFontList.push( "| |              | |" );
    bigFontList.push( "| '--------------' |" );
    bigFontList.push( " '----------------' " );
}